require:
  - rubocop-rails
  - rubocop-rspec

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Max: 12

Style/Documentation:
  Exclude:
    - app/models/application_record.rb
    - app/mailers/application_mailer.rb
    - app/serializers/**/*.rb
    - config/application.rb

Style/MixinUsage:
  Exclude:
    - bin/*

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb
    - spec/**/*.rb

AllCops:
  Exclude:
    - db/**/*rb

RSpec/AnyInstance:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
